name       : perl-list-moreutils
version    : 0.428
release    : 3
source     :
    - https://cpan.metacpan.org/authors/id/R/RE/REHSACK/List-MoreUtils-0.428.tar.gz : 713e0945d5f16e62d81d5f3da2b6a7b14a4ce439f6d3a7de74df1fd166476cc2
license    : Apache-2.0
component  : programming.perl
summary    : Provide the stuff missing in List::Util
description: |
    List::MoreUtils provides some trivial but commonly needed functionality on lists which is not going to go into List::Util.
builddeps  :
    - perl-list-moreutils-xs
    - perl-exporter-tiny
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
