name       : perl-list-moreutils
version    : '0.430'
release    : 9
source     :
    - https://cpan.metacpan.org/authors/id/R/RE/REHSACK/List-MoreUtils-0.430.tar.gz : 63b1f7842cd42d9b538d1e34e0330de5ff1559e4c2737342506418276f646527
license    : Apache-2.0
component  : programming.perl
summary    : Provide the stuff missing in List::Util
description: |
    List::MoreUtils provides some trivial but commonly needed functionality on lists which is not going to go into List::Util.
builddeps  :
    - perl-exporter-tiny
    - perl-list-moreutils-xs
    - perl-test-leaktrace
rundeps    :
    - perl-exporter-tiny
    - perl-list-moreutils-xs
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
