name       : perl-list-moreutils
version    : 0.419
release    : 1
source     :
    - https://cpan.metacpan.org/authors/id/R/RE/REHSACK/List-MoreUtils-0.419.tar.gz : 5f8e65608f5dc583faa6a703d19d277ad46dfc1816e51f8ff34fb8322ed48615
license    : Artisitic-1.0-Perl
component  : programming.perl
summary    : Provide the stuff missing in List::Util
description: |
    List::MoreUtils provides some trivial but commonly needed functionality on lists which is not going to go into List::Util.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
